config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#home'
  resources :cocktails, only: [:index, :show, :new, :create, :edit, :update] do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, :ingredient_id, uniqueness: {
    scope: [:cocktail_id, :ingredient_id]
  }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only:[:show, :edit, :update]
    def index
    @cocktails = Cocktail.all
  end

  def show
    @reviews = Review.all
  end
  
  def new
    # @cocktail = Cocktail.new
  end
  
  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    @cocktail.update(cocktail_params)
    @cocktail.save
    redirect_to cocktail_path(@cocktail)
  end
  
  private
  
  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end
  
  def show
    @dose = Dose.find(params[:id])
  end
  
  def destroy
    @dose = Dose.destroy(params[:id])
    #@cocktail = Cocktail.find(params[:cocktail_id])
    redirect_to cocktail_path(@dose.cocktail)
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :cocktail_params, only:[:new, :create]
    def new
        @review = Review.new
    end

    def create   
        @review = Review.new(set_review)
        @review.cocktail = @cocktail
        if @review.save
            redirect_to cocktail_path(@cocktail)
        else
            render :new
        end
    end

    private

    def cocktail_params
        @cocktail = Cocktail.find(params[:cocktail_id])
    end

    def set_review
        params.require(:review).permit(:content, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_form.html.erb
<div class="form">

    <%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <div class="d-flex justify-content-center">

        <%= f.button :submit, "update", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/cocktails/edit.html.erb
<%= render "shared/header" %>
<div class="back-ground-image height-form">
    <div class="container">
        <div class="edit-form">
            <h2 class="header-title"><%= @cocktail.name %></h2>
            <div class="image-edit">
                <%= cl_image_tag @cocktail.photo.key, height: 400, width: 400, crop: :fill %>
            </div>
            <div class="form mt-4">
                <%= simple_form_for(@cocktail) do |f| %>
                <%= f.input :description, label: "Please edit your description", label_html: { class: "label-desc" } %>
                <div class="d-flex justify-content-center">
                    <%= f.button :submit, "update", class: "btn btn-primary" %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/cocktails/home.html.erb
<div class="homepage" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://i.pinimg.com/originals/b9/4d/4f/b94d4f336d6cdbbc9332bd15027fd3bc.jpg);">
    <div class="container">
        <h1> CoCo Cocktail</h1>
        <p>Enjoy your creativity </p>
        <a class="click-here btn btn-flat" href="/cocktails">Discover more</a>
    </div>
</div>

app/views/cocktails/index.html.erb
<%= render "shared/header" %>
<div class="back-ground-image">
    <div class="container">
        <h1 class='text-center pt-4'>Cocktails</h1>
        <div class="cocktail-index row">
            <% @cocktails.each do |cocktail| %>
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="cocktail-card">
                    <div class="image">
                        <%= cl_image_tag cocktail.photo.key, class: "card-img-top rounded-lg", height: 300, width: 300, crop: :fill%>
                    </div>
                    <div class="card-body row  space-between">
                        <div class="card-body_text col">
                            <h3><%= link_to cocktail.name, cocktail_path(cocktail)%></h3>
                        </div>
                        <div class="card-body_star  col">
                            <% sum = 0 %>
                            <% i = 0 %>
                            <% cocktail.reviews.each_with_index do |review, index| %>
                            <% sum += review.rating %>
                            <% i += 1 %>
                            <% end %>
                            <% if i == 0 %>
                            <p>No Rated</p>
                            <% else %>
                            <p class="pstar"><%= "⭐" * (sum / i) %><%= '☆'* (5 - (sum/i)) %></p>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
            <div style="height: 70px;">
            </div>
        </div>
    </div>
</div>
<%= render 'shared/footer' %>

app/views/cocktails/new.html.erb
<%= render "shared/header" %>
<div class="back-ground-image height-form">
    <div class="container">
        <div class="form">
            <h2 class="text-center header-title"> Add a New Cocktail </h2>
            <div class="from-inputs">
                <%= simple_form_for (@cocktail) do |f| %>
                <%= f.input :name %>
                <%= f.input :description %>
                <%= f.input :photo, as: :file %>
                <div class="d-flex justify-content-center">
                    <%= f.button :submit , "Submit", class: "btn btn-primary"%>
                </div>
            </div>

            <% end %>
        </div>
    </div>
</div>

app/views/cocktails/show.html.erb
<%= render "shared/header" %>
<div class="back-ground-image">
    <div class="container">
        <div class="show-cocktail">
            <h1><%= @cocktail.name %> </h1>

            <div class="row">
                <div class="image-show col-lg-5 col-sm-6">
                    <%= cl_image_tag @cocktail.photo.key, height: 500, width: 400, crop: :fill %>
                </div>
                <div class="dose-desc col-lg-7 col-sm-6">
                    <div class="dose">
                        <h3>Ingredient</h3>
                        <div class="list">
                            <ul>
                                <% @cocktail.doses.each do |dose| %>
                                <li><i class="fas fa-cocktail"> </i>
                                    <strong>Does: </strong> <em><%= dose.ingredient.name%></em> <strong> Description:</strong> <em><%= dose.description%></em> <%= link_to "", dose_path(dose), method: :delete, class: 'fas fa-trash-alt' %>
                                </li>
                                <% end %>
                            </ul>
                        </div>
                        <div class="button">
                            <%= link_to "Add Ingredient", new_cocktail_dose_path(@cocktail), class: 'btn btn-primary'%>
                        </div>
                    </div>

                    <br><br><br><br>
                    <div class="description">
                        <h3>Description</h3>
                        <p><%= @cocktail.description %></p>
                        <%= link_to  "Edit description", edit_cocktail_path(@cocktail),  class: 'btn btn-primary'%>
                    </div>
                </div>
            </div>

            <div class="review">
                <h3>Reviews</h3>
                <% if @cocktail.reviews.empty? %>
                <p> There is no review, Do you want to add a new one?</p>
                <% else %>
                <div class="list list-review">
                    <ul>
                        <% @cocktail.reviews.each do |review| %>
                        <div class="review-list">
                            <li id="star"> <%= ' ⭐️ ' * review.rating%><%= '☆'* (5 - review.rating.to_i)  %> </li>
                            <li> <i class="fas fa-search"></i> <%= review.content%></li>
                        </div>
                        <% end %>
                    </ul>
                    <% end %>
                </div>
                <%= link_to "Add new review", new_cocktail_review_path(@cocktail), class: 'btn btn-primary' %>
            </div>
            <%
=begin%>
            <%= render "reviews/new" %>



            <button type="button" onclick="document.getElementById('review-form').style.display='block'; this.style.visibility='hidden';" , class="btn btn-primary my-2">Add a review</button>
            <%
=end%>
        </div>
    </div>
</div>

app/views/doses/new.html.erb
<%= render "shared/header" %>
<div class="back-ground-image height-form">
    <div class="container" id="dose-form">
        <h2 class="text-center">Add Your Favorite Ingredient</h2>
        <div class="form justify-content-center">
            <%= simple_form_for [@cocktail, @dose] do |f| %>
            <%= f.association :ingredient, collection: Ingredient.all  %>
            <%= f.input :description %>
            <div class="d-flex justify-content-center">
                <%=  f.button :submit, "Submit", class: "btn btn-primary rounded"%>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/doses/show.html.erb
<h1><%= @dose.description %> <%= @dose.ingredient.name %></h1>
<p><%= link_to "delete this dose", dose_path(@dose) %></p>
<p><%= link_to "back to cocktail", cocktail_path(params[:id]) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>

<body>

    <%= yield %>

    </div>
</body>

</html>

app/views/reviews/new.html.erb
<div class="back-ground-image">
    <div class="back-ground-image height-form">
        <div class="container">
            <h2 class="text-center header-title"> if you had a good experiace with this cocktail please write a review and rate it.</h2>
            <div class="form">
                <%= simple_form_for [@cocktail, @review] do |f| %>
                <%= f.input :rating, type: 'select', collection: [1, 2, 3, 4, 5]  %>
                <%= f.input :content %>
                <div class="d-flex justify-content-center">
                    <%=  f.button :submit, "Submit", class: "btn btn-primary rounded"%>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="container">
        <div class="footer-up">
            <div class="info-footer">
                <i class="fas fa-envelope" id='envelope-footer'></i>
                <a href="Email:masoud.arabi2030@gmail.com">masoud.arabi2030@gmail.com</a>
            </div>
            <div class="social-footer">
                <a id="git" , href="https://github.com/renaudaf" , target="_blank"><i class="fab fa-github"></i></a>
                <a id="linkedin" , href="https://www.linkedin.com/in/renaud-archer-fortin/" , target="_blank"><i class="fab fa-linkedin"></i></a>
            </div>
            <div class="legal-footer">
                <p>© Copyright 2020 MSH, All Rights Reserved.</p>
            </div>
        </div>
    </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar ">
    <a class="navbar-brand" href="/cocktails">
        <i class="fas fa-glass-martini-alt"></i>
        CoCo Cocktail
    </a>
    <a href="/cocktails/new" class='add-cocktail'>Add A New Cocktail</a>
</nav>